name: 'Cloudflare Warp setup'
description: 'Set up Cloudflare Warp on Github actions running ubuntu'

runs:
  using: composite
  steps:
    - name: Install Warp
      continue-on-error: true
      run: |
        sudo apt install curl wget -y
        wget https://pkg.cloudflareclient.com/uploads/cloudflare_warp_2022_5_346_1_amd64_ea02be46df.deb -O warp.deb && sudo dpkg -i warp.deb || true ; sudo apt-get -f install -y 
      shell: bash
    - name: Connect to Warp
      run: |
        warp-cli --accept-tos register
        warp-cli --accept-tos connect
        warp-cli --accept-tos set-mode warp+doh && sleep 1s
      shell: bash
    - name: Connection stats
      run: |
        curl https://cloudflare.com/cdn-cgi/trace
      shell: bash